=== jaffbeto/la2eden/dist/gameserver/datapack/xsd/PrimeShop.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="list">
        <xs:complexType>
            <xs:sequence minOccurs="1" maxOccurs="1" >
                <xs:element name="item" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="brId" type="xs:long" use="required" />
                        <xs:attribute name="itemId" type="xs:integer" use="required" />
                        <xs:attribute name="count" type="xs:integer" use="required" />
                        <xs:attribute name="cat" type="xs:integer" use="required" />
                        <xs:attribute name="price" type="xs:integer" use="required" />
                        <xs:attribute name="event" type="xs:boolean" use="required" />
                        <xs:attribute name="best" type="xs:boolean" use="required" />
                        <xs:attribute name="sale_start_date" type="xs:string" />
                        <xs:attribute name="sale_end_date" type="xs:string" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== jaffbeto/la2eden/dist/gameserver/datapack/PrimeShop.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--   Categories (cat):     -->
<!--      1 - enchant        -->
<!--      2 - supplies       -->
<!--      3 - decorating     -->
<!--      4 - package        -->
<!--      5 - others         -->
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/PrimeShop.xsd">
    <!-- OTHERS -->
    <!-- Small fortuna box -->
    <item brId="1080001" itemId="22000" count="1" cat="5" price="135" event="false" best="true" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Middle fortuna box -->
    <item brId="1080002" itemId="22001" count="1" cat="5" price="270" event="false" best="true" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Large fortuna box -->
    <item brId="1080003" itemId="22002" count="1" cat="5" price="405" event="false" best="true" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Small fortuna cube -->
    <item brId="1080004" itemId="22003" count="1" cat="5" price="81" event="false" best="true" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Middle fortuna cube -->
    <item brId="1080005" itemId="22004" count="1" cat="5" price="216" event="false" best="true" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Large fortuna cube -->
    <item brId="1080006" itemId="22005" count="1" cat="5" price="324" event="false" best="true" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Feather of Blessing -->
    <item brId="1080184" itemId="10649" count="1" cat="5" price="500" event="false" best="true" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />

    <!-- SUPPLIES -->
    <!-- Powerful Healing Potion -->
    <item brId="1080007" itemId="22025" count="1" cat="2" price="3" event="false" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- High-grade Healing Potion -->
    <item brId="1080008" itemId="22026" count="1" cat="2" price="1" event="false" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Secret medicine of Will - D grade -->
    <item brId="1080009" itemId="22027" count="1" cat="2" price="1" event="false" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Secret medicine of Will - C grade -->
    <item brId="1080010" itemId="22028" count="1" cat="2" price="1" event="false" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Secret medicine of Will - B grade -->
    <item brId="1080011" itemId="22029" count="1" cat="2" price="1" event="false" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Secret medicine of Will - A grade -->
    <item brId="1080012" itemId="22030" count="1" cat="2" price="1" event="false" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Secret medicine of Will - S grade -->
    <item brId="1080013" itemId="22031" count="1" cat="2" price="1" event="false" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Secret medicine of Life - D grade -->
    <item brId="1080014" itemId="22032" count="1" cat="2" price="1" event="false" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Secret medicine of Life - C grade -->
    <item brId="1080015" itemId="22033" count="1" cat="2" price="3" event="false" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Secret medicine of Life - B grade -->
    <item brId="1080016" itemId="22034" count="1" cat="2" price="9" event="false" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Secret medicine of Life - A grade -->
    <item brId="1080017" itemId="22035" count="1" cat="2" price="20" event="false" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Secret medicine of Life - S grade -->
    <item brId="1080018" itemId="22036" count="1" cat="2" price="80" event="false" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Potion of Will -->
    <item brId="1080019" itemId="22037" count="1" cat="2" price="4" event="false" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Healing medicine for Mana -->
    <item brId="1080020" itemId="22038" count="1" cat="2" price="4" event="false" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Sweet Fruit Cocktail -->
    <item brId="1080199" itemId="20393" count="1" cat="2" price="50" event="false" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Fresh Fruit Cocktail -->
    <item brId="1080200" itemId="20394" count="1" cat="2" price="50" event="false" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Wind Walk Scroll -->
    <item brId="1080021" itemId="22039" count="1" cat="2" price="8" event="false" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Haste Scroll -->
    <item brId="1080022" itemId="22040" count="1" cat="2" price="8" event="false" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Might Scroll -->
    <item brId="1080023" itemId="22041" count="1" cat="2" price="8" event="false" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Shield Scroll -->
    <item brId="1080024" itemId="22042" count="1" cat="2" price="8" event="false" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Death Whisper Scroll -->
    <item brId="1080025" itemId="22043" count="1" cat="2" price="8" event="false" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Guidance Scroll -->
    <item brId="1080026" itemId="22044" count="1" cat="2" price="8" event="false" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Empower Scrol -->
    <item brId="1080027" itemId="22045" count="1" cat="2" price="8" event="false" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Grater Acumen Scroll -->
    <item brId="1080028" itemId="22046" count="1" cat="2" price="8" event="false" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Vampiric Rage Scroll	 -->
    <item brId="1080029" itemId="22047" count="1" cat="2" price="8" event="false" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Bless the Body Scroll -->
    <item brId="1080030" itemId="22048" count="1" cat="2" price="8" event="false" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Berserker Spirit Scroll -->
    <item brId="1080031" itemId="22049" count="1" cat="2" price="8" event="false" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Magic Barrier Scroll -->
    <item brId="1080032" itemId="22050" count="1" cat="2" price="8" event="false" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Bless the Soul Scrol -->
    <item brId="1080033" itemId="22051" count="1" cat="2" price="8" event="false" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Clarity Scroll -->
    <item brId="1080034" itemId="22052" count="1" cat="2" price="8" event="false" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Wild Magic Scroll -->
    <item brId="1080035" itemId="22053" count="1" cat="2" price="8" event="false" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />

    <!-- EVENT -->
    <!-- Rune of Experience Points 24hs -->
    <item brId="1080036" itemId="22054" count="1" cat="5" price="20" event="true" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Rune of Experience Points 168hs -->
    <item brId="1080037" itemId="22055" count="1" cat="5" price="50" event="true" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Rune of Experience Points 336hs -->
    <item brId="1080038" itemId="22056" count="1" cat="5" price="80" event="true" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Rune of Experience Points 720hs -->
    <item brId="1080039" itemId="22057" count="1" cat="5" price="100" event="true" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Rune of SP 24hs -->
    <item brId="1080040" itemId="22058" count="1" cat="5" price="20" event="true" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Rune of SP 168hs -->
    <item brId="1080041" itemId="22059" count="1" cat="5" price="50" event="true" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Rune of SP 336hs -->
    <item brId="1080042" itemId="22060" count="1" cat="5" price="80" event="true" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Rune of SP 720hs -->
    <item brId="1080043" itemId="22061" count="1" cat="5" price="100" event="true" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />

    <!-- PACKAGE -->
    <!-- Bone Bolt Container -->
    <item brId="1080056" itemId="22149" count="1" cat="4" price="21" event="false" best="false" sale_start_date="2017.11.05 09:00" sale_end_date="2020.12.05 18:00" />
    <!-- Steel Bolt Container -->
